version: 2
models: 
  - name: fct_orders
    columns:
      - name: order_id
        testes:
          - unique
          - not_null
      - name: customer_unique_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_unique_id